DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(32) UNIQUE  NOT NULL,
    email        VARCHAR(256) UNIQUE NOT NULL,
    password     VARCHAR             NOT NULL,
    max_accounts INT                 NOT NULL
);

CREATE TABLE accounts
(
    number   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    amount   BIGINT DEFAULT 0                               NOT NULL,
    currency VARCHAR(3)                                     NOT NULL
);

CREATE TABLE operations
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_number BIGINT REFERENCES accounts (number) ON DELETE CASCADE,
    amount         BIGINT    NOT NULL,
    operation_type VARCHAR   NOT NULL,
    date_time      TIMESTAMP NOT NULL
);